### ISSUE TITLE
Address getting recorded wrong

### ISSUE THREAD

**Issue by equivalentideas** [planningalerts-scrapers/parramatta#1]
Unfortunately the councils da system is printing wrong addresses into the feed for applications like this one http://eplanning.parracity.nsw.gov.au/Pages/XC.Track/SearchApplication.aspx?id=391647

We're collecting "0 Gollan Avenue OATLANDS NSW 2117" instead of "32 Gollan Ave Oatlands NSW". Here's what [the feed](http://eplanning.parracity.nsw.gov.au/Pages/xc.Track/SearchApplication.aspx?o=rss) looks like:

```
    <item>
      <author>Pbi Na Mao</author>
      <category>CCP/358/2016</category>
      <description>0  Gollan Avenue OATLANDS NSW 2117. 31 Golla Ave, Oatlands - Demolition of an existing building and construction of a two storey dwelling</description>
      <link>?id=393451</link>
      <pubDate>16/Jun/2016</pubDate>
      <pubDateParsed>2016-06-16T00:00:00</pubDateParsed>
      <title>CCP/358/2016</title>
    </item>
```

It looks really tricky to deal with because this isn't common. I’ve asked the brilliant citizen who reported this to ask the council to fix it.

In the mean time I'm going to fix the applications manually in PlanningAlerts so at least they show up in search for people.

**Comment by equivalentideas** [comment]
:( we've collected 444 applications with a 0 street number from this council. Heaps of people will have missed planning proposals near them because of this.

I'm just going to update the ones on Gollan street for this person, too many to fix otherwise.

**Comment by henare** [comment]
@equivalentideas have you turned off auto-run? If not, please do that so we don't keep collecting Bad Data:tm:

**Comment by equivalentideas** [comment]
> @equivalentideas have you turned off auto-run? If not, please do that so we don't keep collecting Bad Data™️

Done 👍

**Comment by LoveMyData** [comment]
Turned off Auto-Run again, as now the description not receiving proper data. A lot of them saying 'ePathway' as description

**Comment by alexmck** [comment]
Is there any consensus on what to do with these issues? As a resident in the area, these alerts are invaluable.

The street address as 0 is not a big issue. Those proposals were still sent.

The ePathway description seems to be more of a place holder from the council, and occurs in a few instances:

- Applications were from old councils (eg Hornsby) which are now part of Parramatta
- Applications were determined by the state government

I would argue that auto-run should be turned back on, as the benefit to the community is far greater than these smaller issues.

**Comment by henare** [comment]
@alexmck we'd normally agree that it's better to get something than nothing however it wasn't the case here as you can see above:

>Heaps of people will have missed planning proposals near them because of this.

The solution here is to fix the scraper. It shouldn't be much work. If you'd like to take this on that would be awesome :star2: You can also make a [tax-deductible donation](https://www.planningalerts.org.au/donate) to support the work if you don't have the time or skills yourself :green_heart:

**Comment by alexmck** [comment]
@henare The alerts were still sending fine, even with a street address of 0.
<img width="403" alt="screen shot 2017-03-09 at 12 03 03 pm" src="https://cloud.githubusercontent.com/assets/4444107/23731258/a5ba7bc6-04c0-11e7-92a1-dd7feb6ba2ff.png">
In the current RSS feed, there are a total of 9 applications which have a street number of 0. Of them, only 1 then has the correct address in the description.

**Comment by LoveMyData** [comment]
[PR #2](https://github.com/planningalerts-scrapers/parramatta/pull/2) should fixed most issue and we can re-enabled this scraper once accepted.

Address with 0.... can't fix that because the feed actually provide address number starting with zero. However, this [PR #2](https://github.com/planningalerts-scrapers/parramatta/pull/2) fixed couple other issues like 'ePathway' in description and junk data in the 'address' field.

Tested with past 90 days worth of DAs and they all parsed correctly.

**Comment by equivalentideas** [comment]
@LoveMyData has fixed this :) @alexmck you should be receiving lots of DA's tomorrow ;)

I've switched autorun on.
